#!/usr/bin/ruby

names = [
  'dropbox.com',
  'dropboxstatic.com',
  'web.whatsapp.com',
  'venus.web.telegram.org',
  'pluto.web.telegram.org',
  'torguard.net',
  'thechive.com',
  'postimages.org',
  'photos.google.com',
  'postimgs.org'
]

ips = (names.map do |name|
  output = `host #{name}`
  output.scan(/\d+(?:\.\d+)+/)
end).flatten.uniq

ips << '149.154.175.50' # telegram desktop

ips.map do |ip|
  puts "sudo ip route add #{ip}/32 via 192.168.128.1 dev wlp6s0"
end