actions:
  post:
    i3: i3-msg {0}
    reload_resources: xrdb -merge ~/.Xresources
    ruby: ruby {0}
config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: link
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
  d_fonts:
    dst: ~/.fonts
    link: link
    src: fonts
  f_ackrc:
    dst: ~/.ackrc
    link: link
    src: ackrc
  f_dunstrc:
    dst: ~/.config/dunst/dunstrc
    link: link
    src: config/dunst/dunstrc
  f_profile:
    dst: ~/.profile
    link: link
    src: zprofile
  f_settings.json:
    dst: ~/.config/Code/User/settings.json
    link: link
    src: config/Code/User/settings.json
  f_xdefaults:
    actions:
    - reload_resources
    dst: ~/.Xdefaults
    src: Xdefaults
  f_xresources:
    actions:
    - reload_resources
    dst: ~/.Xresources
    src: Xdefaults
  f_zprofile:
    dst: ~/.zprofile
    link: link
    src: zprofile
  f_zshrc:
    dst: ~/.zshrc
    link: link
    src: zshrc
  i3_config:
    actions:
    - i3 restart
    dst: ~/.config/i3
    src: config/i3
  my_scripts:
    dst: ~/Applications/scripts
    src: scripts
  nativefier:
    actions:
    - ruby dotfiles/nativefier/generate.rb
    dst: ~/Applications/nativefier/apps.yml
    src: nativefier/apps.yml
profiles:
  kerrigan:
    dotfiles:
    - i3_config
    - f_ackrc
    - nativefier
    - f_zprofile
    - f_profile
    - f_dunstrc
    - my_scripts
    - f_settings.json
    - f_zshrc
    - f_xdefaults
    - f_xresources
    - d_fonts
